//
//  Country.swift
//  currency-exchange-app
//
//  Created by jay on 9/9/26.
//

import Foundation

struct Country {
    let name: String
    let code: String
    let currencyCode: String
    let flagEmoji: String
}

extension Country {
    static var countries: [Country] {
        return [
            Country(name: "Afghanistan", code: "AF", currencyCode: "AFN", flagEmoji: "🇦🇫"),
            Country(name: "Albania", code: "AL", currencyCode: "ALL", flagEmoji: "🇦🇱"),
            Country(name: "Algeria", code: "DZ", currencyCode: "DZD", flagEmoji: "🇩🇿"),
            Country(name: "Andorra", code: "AD", currencyCode: "EUR", flagEmoji: "🇦🇩"),
            Country(name: "Angola", code: "AO", currencyCode: "AOA", flagEmoji: "🇦🇴"),
            Country(name: "Antigua and Barbuda", code: "AG", currencyCode: "XCD", flagEmoji: "🇦🇬"),
            Country(name: "Argentina", code: "AR", currencyCode: "ARS", flagEmoji: "🇦🇷"),
            Country(name: "Armenia", code: "AM", currencyCode: "AMD", flagEmoji: "🇦🇲"),
            Country(name: "Australia", code: "AU", currencyCode: "AUD", flagEmoji: "🇦🇺"),
            Country(name: "Austria", code: "AT", currencyCode: "EUR", flagEmoji: "🇦🇹"),
            Country(name: "Azerbaijan", code: "AZ", currencyCode: "AZN", flagEmoji: "🇦🇿"),
            Country(name: "Bahamas", code: "BS", currencyCode: "BSD", flagEmoji: "🇧🇸"),
            Country(name: "Bahrain", code: "BH", currencyCode: "BHD", flagEmoji: "🇧🇭"),
            Country(name: "Bangladesh", code: "BD", currencyCode: "BDT", flagEmoji: "🇧🇩"),
            Country(name: "Barbados", code: "BB", currencyCode: "BBD", flagEmoji: "🇧🇧"),
            Country(name: "Belarus", code: "BY", currencyCode: "BYN", flagEmoji: "🇧🇾"),
            Country(name: "Belgium", code: "BE", currencyCode: "EUR", flagEmoji: "🇧🇪"),
            Country(name: "Belize", code: "BZ", currencyCode: "BZD", flagEmoji: "🇧🇿"),
            Country(name: "Benin", code: "BJ", currencyCode: "XOF", flagEmoji: "🇧🇯"),
            Country(name: "Bhutan", code: "BT", currencyCode: "BTN", flagEmoji: "🇧🇹"),
            Country(name: "Bolivia", code: "BO", currencyCode: "BOB", flagEmoji: "🇧🇴"),
            Country(name: "Bosnia and Herzegovina", code: "BA", currencyCode: "BAM", flagEmoji: "🇧🇦"),
            Country(name: "Botswana", code: "BW", currencyCode: "BWP", flagEmoji: "🇧🇼"),
            Country(name: "Brazil", code: "BR", currencyCode: "BRL", flagEmoji: "🇧🇷"),
            Country(name: "Brunei", code: "BN", currencyCode: "BND", flagEmoji: "🇧🇳"),
            Country(name: "Bulgaria", code: "BG", currencyCode: "BGN", flagEmoji: "🇧🇬"),
            Country(name: "Burkina Faso", code: "BF", currencyCode: "XOF", flagEmoji: "🇧🇫"),
            Country(name: "Burundi", code: "BI", currencyCode: "BIF", flagEmoji: "🇧🇮"),
            Country(name: "Cabo Verde", code: "CV", currencyCode: "CVE", flagEmoji: "🇨🇻"),
            Country(name: "Cambodia", code: "KH", currencyCode: "KHR", flagEmoji: "🇰🇭"),
            Country(name: "Cameroon", code: "CM", currencyCode: "XAF", flagEmoji: "🇨🇲"),
            Country(name: "Canada", code: "CA", currencyCode: "CAD", flagEmoji: "🇨🇦"),
            Country(name: "Central African Republic", code: "CF", currencyCode: "XAF", flagEmoji: "🇨🇫"),
            Country(name: "Chad", code: "TD", currencyCode: "XAF", flagEmoji: "🇹🇩"),
            Country(name: "Chile", code: "CL", currencyCode: "CLP", flagEmoji: "🇨🇱"),
            Country(name: "China", code: "CN", currencyCode: "CNY", flagEmoji: "🇨🇳"),
            Country(name: "Colombia", code: "CO", currencyCode: "COP", flagEmoji: "🇨🇴"),
            Country(name: "Comoros", code: "KM", currencyCode: "KMF", flagEmoji: "🇰🇲"),
            Country(name: "Congo (Brazzaville)", code: "CG", currencyCode: "XAF", flagEmoji: "🇨🇬"),
            Country(name: "Congo (Kinshasa)", code: "CD", currencyCode: "CDF", flagEmoji: "🇨🇩"),
            Country(name: "Costa Rica", code: "CR", currencyCode: "CRC", flagEmoji: "🇨🇷"),
            Country(name: "Côte d'Ivoire", code: "CI", currencyCode: "XOF", flagEmoji: "🇨🇮"),
            Country(name: "Croatia", code: "HR", currencyCode: "EUR", flagEmoji: "🇭🇷"),
            Country(name: "Cuba", code: "CU", currencyCode: "CUP", flagEmoji: "🇨🇺"),
            Country(name: "Cyprus", code: "CY", currencyCode: "EUR", flagEmoji: "🇨🇾"),
            Country(name: "Czechia", code: "CZ", currencyCode: "CZK", flagEmoji: "🇨🇿"),
            Country(name: "Denmark", code: "DK", currencyCode: "DKK", flagEmoji: "🇩🇰"),
            Country(name: "Djibouti", code: "DJ", currencyCode: "DJF", flagEmoji: "🇩🇯"),
            Country(name: "Dominica", code: "DM", currencyCode: "XCD", flagEmoji: "🇩🇲"),
            Country(name: "Dominican Republic", code: "DO", currencyCode: "DOP", flagEmoji: "🇩🇴"),
            Country(name: "Ecuador", code: "EC", currencyCode: "USD", flagEmoji: "🇪🇨"),
            Country(name: "Egypt", code: "EG", currencyCode: "EGP", flagEmoji: "🇪🇬"),
            Country(name: "El Salvador", code: "SV", currencyCode: "USD", flagEmoji: "🇸🇻"),
            Country(name: "Equatorial Guinea", code: "GQ", currencyCode: "XAF", flagEmoji: "🇬🇶"),
            Country(name: "Eritrea", code: "ER", currencyCode: "ERN", flagEmoji: "🇪🇷"),
            Country(name: "Estonia", code: "EE", currencyCode: "EUR", flagEmoji: "🇪🇪"),
            Country(name: "Eswatini", code: "SZ", currencyCode: "SZL", flagEmoji: "🇸🇿"),
            Country(name: "Ethiopia", code: "ET", currencyCode: "ETB", flagEmoji: "🇪🇹"),
            Country(name: "Fiji", code: "FJ", currencyCode: "FJD", flagEmoji: "🇫🇯"),
            Country(name: "Finland", code: "FI", currencyCode: "EUR", flagEmoji: "🇫🇮"),
            Country(name: "France", code: "FR", currencyCode: "EUR", flagEmoji: "🇫🇷"),
            Country(name: "Gabon", code: "GA", currencyCode: "XAF", flagEmoji: "🇬🇦"),
            Country(name: "Gambia", code: "GM", currencyCode: "GMD", flagEmoji: "🇬🇲"),
            Country(name: "Georgia", code: "GE", currencyCode: "GEL", flagEmoji: "🇬🇪"),
            Country(name: "Germany", code: "DE", currencyCode: "EUR", flagEmoji: "🇩🇪"),
            Country(name: "Ghana", code: "GH", currencyCode: "GHS", flagEmoji: "🇬🇭"),
            Country(name: "Greece", code: "GR", currencyCode: "EUR", flagEmoji: "🇬🇷"),
            Country(name: "Grenada", code: "GD", currencyCode: "XCD", flagEmoji: "🇬🇩"),
            Country(name: "Guatemala", code: "GT", currencyCode: "GTQ", flagEmoji: "🇬🇹"),
            Country(name: "Guinea", code: "GN", currencyCode: "GNF", flagEmoji: "🇬🇳"),
            Country(name: "Guinea-Bissau", code: "GW", currencyCode: "XOF", flagEmoji: "🇬🇼"),
            Country(name: "Guyana", code: "GY", currencyCode: "GYD", flagEmoji: "🇬🇾"),
            Country(name: "Haiti", code: "HT", currencyCode: "HTG", flagEmoji: "🇭🇹"),
            Country(name: "Honduras", code: "HN", currencyCode: "HNL", flagEmoji: "🇭🇳"),
            Country(name: "Hungary", code: "HU", currencyCode: "HUF", flagEmoji: "🇭🇺"),
            Country(name: "Iceland", code: "IS", currencyCode: "ISK", flagEmoji: "🇮🇸"),
            Country(name: "India", code: "IN", currencyCode: "INR", flagEmoji: "🇮🇳"),
            Country(name: "Indonesia", code: "ID", currencyCode: "IDR", flagEmoji: "🇮🇩"),
            Country(name: "Iran", code: "IR", currencyCode: "IRR", flagEmoji: "🇮🇷"),
            Country(name: "Iraq", code: "IQ", currencyCode: "IQD", flagEmoji: "🇮🇶"),
            Country(name: "Ireland", code: "IE", currencyCode: "EUR", flagEmoji: "🇮🇪"),
            Country(name: "Israel", code: "IL", currencyCode: "ILS", flagEmoji: "🇮🇱"),
            Country(name: "Italy", code: "IT", currencyCode: "EUR", flagEmoji: "🇮🇹"),
            Country(name: "Jamaica", code: "JM", currencyCode: "JMD", flagEmoji: "🇯🇲"),
            Country(name: "Japan", code: "JP", currencyCode: "JPY", flagEmoji: "🇯🇵"),
            Country(name: "Jordan", code: "JO", currencyCode: "JOD", flagEmoji: "🇯🇴"),
            Country(name: "Kazakhstan", code: "KZ", currencyCode: "KZT", flagEmoji: "🇰🇿"),
            Country(name: "Kenya", code: "KE", currencyCode: "KES", flagEmoji: "🇰🇪"),
            Country(name: "Kiribati", code: "KI", currencyCode: "AUD", flagEmoji: "🇰🇮"),
            Country(name: "Kuwait", code: "KW", currencyCode: "KWD", flagEmoji: "🇰🇼"),
            Country(name: "Kyrgyzstan", code: "KG", currencyCode: "KGS", flagEmoji: "🇰🇬"),
            Country(name: "Laos", code: "LA", currencyCode: "LAK", flagEmoji: "🇱🇦"),
            Country(name: "Latvia", code: "LV", currencyCode: "EUR", flagEmoji: "🇱🇻"),
            Country(name: "Lebanon", code: "LB", currencyCode: "LBP", flagEmoji: "🇱🇧"),
            Country(name: "Lesotho", code: "LS", currencyCode: "LSL", flagEmoji: "🇱🇸"),
            Country(name: "Liberia", code: "LR", currencyCode: "LRD", flagEmoji: "🇱🇷"),
            Country(name: "Libya", code: "LY", currencyCode: "LYD", flagEmoji: "🇱🇾"),
            Country(name: "Liechtenstein", code: "LI", currencyCode: "CHF", flagEmoji: "🇱🇮"),
            Country(name: "Lithuania", code: "LT", currencyCode: "EUR", flagEmoji: "🇱🇹"),
            Country(name: "Luxembourg", code: "LU", currencyCode: "EUR", flagEmoji: "🇱🇺"),
            Country(name: "Madagascar", code: "MG", currencyCode: "MGA", flagEmoji: "🇲🇬"),
            Country(name: "Malawi", code: "MW", currencyCode: "MWK", flagEmoji: "🇲🇼"),
            Country(name: "Malaysia", code: "MY", currencyCode: "MYR", flagEmoji: "🇲🇾"),
            Country(name: "Maldives", code: "MV", currencyCode: "MVR", flagEmoji: "🇲🇻"),
            Country(name: "Mali", code: "ML", currencyCode: "XOF", flagEmoji: "🇲🇱"),
            Country(name: "Malta", code: "MT", currencyCode: "EUR", flagEmoji: "🇲🇹"),
            Country(name: "Marshall Islands", code: "MH", currencyCode: "USD", flagEmoji: "🇲🇭"),
            Country(name: "Mauritania", code: "MR", currencyCode: "MRU", flagEmoji: "🇲🇷"),
            Country(name: "Mauritius", code: "MU", currencyCode: "MUR", flagEmoji: "🇲🇺"),
            Country(name: "Mexico", code: "MX", currencyCode: "MXN", flagEmoji: "🇲🇽"),
            Country(name: "Micronesia", code: "FM", currencyCode: "USD", flagEmoji: "🇫🇲"),
            Country(name: "Moldova", code: "MD", currencyCode: "MDL", flagEmoji: "🇲🇩"),
            Country(name: "Monaco", code: "MC", currencyCode: "EUR", flagEmoji: "🇲🇨"),
            Country(name: "Mongolia", code: "MN", currencyCode: "MNT", flagEmoji: "🇲🇳"),
            Country(name: "Montenegro", code: "ME", currencyCode: "EUR", flagEmoji: "🇲🇪"),
            Country(name: "Morocco", code: "MA", currencyCode: "MAD", flagEmoji: "🇲🇦"),
            Country(name: "Mozambique", code: "MZ", currencyCode: "MZN", flagEmoji: "🇲🇿"),
            Country(name: "Myanmar", code: "MM", currencyCode: "MMK", flagEmoji: "🇲🇲"),
            Country(name: "Namibia", code: "NA", currencyCode: "NAD", flagEmoji: "🇳🇦"),
            Country(name: "Nauru", code: "NR", currencyCode: "AUD", flagEmoji: "🇳🇷"),
            Country(name: "Nepal", code: "NP", currencyCode: "NPR", flagEmoji: "🇳🇵"),
            Country(name: "Netherlands", code: "NL", currencyCode: "EUR", flagEmoji: "🇳🇱"),
            Country(name: "New Zealand", code: "NZ", currencyCode: "NZD", flagEmoji: "🇳🇿"),
            Country(name: "Nicaragua", code: "NI", currencyCode: "NIO", flagEmoji: "🇳🇮"),
            Country(name: "Niger", code: "NE", currencyCode: "XOF", flagEmoji: "🇳🇪"),
            Country(name: "Nigeria", code: "NG", currencyCode: "NGN", flagEmoji: "🇳🇬"),
            Country(name: "North Korea", code: "KP", currencyCode: "KPW", flagEmoji: "🇰🇵"),
            Country(name: "North Macedonia", code: "MK", currencyCode: "MKD", flagEmoji: "🇲🇰"),
            Country(name: "Norway", code: "NO", currencyCode: "NOK", flagEmoji: "🇳🇴"),
            Country(name: "Oman", code: "OM", currencyCode: "OMR", flagEmoji: "🇴🇲"),
            Country(name: "Pakistan", code: "PK", currencyCode: "PKR", flagEmoji: "🇵🇰"),
            Country(name: "Palau", code: "PW", currencyCode: "USD", flagEmoji: "🇵🇼"),
            Country(name: "Panama", code: "PA", currencyCode: "PAB", flagEmoji: "🇵🇦"),
            Country(name: "Papua New Guinea", code: "PG", currencyCode: "PGK", flagEmoji: "🇵🇬"),
            Country(name: "Paraguay", code: "PY", currencyCode: "PYG", flagEmoji: "🇵🇾"),
            Country(name: "Peru", code: "PE", currencyCode: "PEN", flagEmoji: "🇵🇪"),
            Country(name: "Philippines", code: "PH", currencyCode: "PHP", flagEmoji: "🇵🇭"),
            Country(name: "Poland", code: "PL", currencyCode: "PLN", flagEmoji: "🇵🇱"),
            Country(name: "Portugal", code: "PT", currencyCode: "EUR", flagEmoji: "🇵🇹"),
            Country(name: "Qatar", code: "QA", currencyCode: "QAR", flagEmoji: "🇶🇦"),
            Country(name: "Romania", code: "RO", currencyCode: "RON", flagEmoji: "🇷🇴"),
            Country(name: "Russia", code: "RU", currencyCode: "RUB", flagEmoji: "🇷🇺"),
            Country(name: "Rwanda", code: "RW", currencyCode: "RWF", flagEmoji: "🇷🇼"),
            Country(name: "Saint Kitts and Nevis", code: "KN", currencyCode: "XCD", flagEmoji: "🇰🇳"),
            Country(name: "Saint Lucia", code: "LC", currencyCode: "XCD", flagEmoji: "🇱🇨"),
            Country(name: "Saint Vincent and the Grenadines", code: "VC", currencyCode: "XCD", flagEmoji: "🇻🇨"),
            Country(name: "Samoa", code: "WS", currencyCode: "WST", flagEmoji: "🇼🇸"),
            Country(name: "San Marino", code: "SM", currencyCode: "EUR", flagEmoji: "🇸🇲"),
            Country(name: "Sao Tome and Principe", code: "ST", currencyCode: "STN", flagEmoji: "🇸🇹"),
            Country(name: "Saudi Arabia", code: "SA", currencyCode: "SAR", flagEmoji: "🇸🇦"),
            Country(name: "Senegal", code: "SN", currencyCode: "XOF", flagEmoji: "🇸🇳"),
            Country(name: "Serbia", code: "RS", currencyCode: "RSD", flagEmoji: "🇷🇸"),
            Country(name: "Seychelles", code: "SC", currencyCode: "SCR", flagEmoji: "🇸🇨"),
            Country(name: "Sierra Leone", code: "SL", currencyCode: "SLE", flagEmoji: "🇸🇱"),
            Country(name: "Singapore", code: "SG", currencyCode: "SGD", flagEmoji: "🇸🇬"),
            Country(name: "Slovakia", code: "SK", currencyCode: "EUR", flagEmoji: "🇸🇰"),
            Country(name: "Slovenia", code: "SI", currencyCode: "EUR", flagEmoji: "🇸🇮"),
            Country(name: "Solomon Islands", code: "SB", currencyCode: "SBD", flagEmoji: "🇸🇧"),
            Country(name: "Somalia", code: "SO", currencyCode: "SOS", flagEmoji: "🇸🇴"),
            Country(name: "South Africa", code: "ZA", currencyCode: "ZAR", flagEmoji: "🇿🇦"),
            Country(name: "South Korea", code: "KR", currencyCode: "KRW", flagEmoji: "🇰🇷"),
            Country(name: "South Sudan", code: "SS", currencyCode: "SSP", flagEmoji: "🇸🇸"),
            Country(name: "Spain", code: "ES", currencyCode: "EUR", flagEmoji: "🇪🇸"),
            Country(name: "Sri Lanka", code: "LK", currencyCode: "LKR", flagEmoji: "🇱🇰"),
            Country(name: "Sudan", code: "SD", currencyCode: "SDG", flagEmoji: "🇸🇩"),
            Country(name: "Suriname", code: "SR", currencyCode: "SRD", flagEmoji: "🇸🇷"),
            Country(name: "Sweden", code: "SE", currencyCode: "SEK", flagEmoji: "🇸🇪"),
            Country(name: "Switzerland", code: "CH", currencyCode: "CHF", flagEmoji: "🇨🇭"),
            Country(name: "Syria", code: "SY", currencyCode: "SYP", flagEmoji: "🇸🇾"),
            Country(name: "Taiwan", code: "TW", currencyCode: "TWD", flagEmoji: "🇹🇼"),
            Country(name: "Tajikistan", code: "TJ", currencyCode: "TJS", flagEmoji: "🇹🇯"),
            Country(name: "Tanzania", code: "TZ", currencyCode: "TZS", flagEmoji: "🇹🇿"),
            Country(name: "Thailand", code: "TH", currencyCode: "THB", flagEmoji: "🇹🇭"),
            Country(name: "Timor-Leste", code: "TL", currencyCode: "USD", flagEmoji: "🇹🇱"),
            Country(name: "Togo", code: "TG", currencyCode: "XOF", flagEmoji: "🇹🇬"),
            Country(name: "Tonga", code: "TO", currencyCode: "TOP", flagEmoji: "🇹🇴"),
            Country(name: "Trinidad and Tobago", code: "TT", currencyCode: "TTD", flagEmoji: "🇹🇹"),
            Country(name: "Tunisia", code: "TN", currencyCode: "TND", flagEmoji: "🇹🇳"),
            Country(name: "Turkey", code: "TR", currencyCode: "TRY", flagEmoji: "🇹🇷"),
            Country(name: "Turkmenistan", code: "TM", currencyCode: "TMT", flagEmoji: "🇹🇲"),
            Country(name: "Tuvalu", code: "TV", currencyCode: "AUD", flagEmoji: "🇹🇻"),
            Country(name: "Uganda", code: "UG", currencyCode: "UGX", flagEmoji: "🇺🇬"),
            Country(name: "Ukraine", code: "UA", currencyCode: "UAH", flagEmoji: "🇺🇦"),
            Country(name: "United Arab Emirates", code: "AE", currencyCode: "AED", flagEmoji: "🇦🇪"),
            Country(name: "United Kingdom", code: "GB", currencyCode: "GBP", flagEmoji: "🇬🇧"),
            Country(name: "United States", code: "US", currencyCode: "USD", flagEmoji: "🇺🇸"),
            Country(name: "Uruguay", code: "UY", currencyCode: "UYU", flagEmoji: "🇺🇾"),
            Country(name: "Uzbekistan", code: "UZ", currencyCode: "UZS", flagEmoji: "🇺🇿"),
            Country(name: "Vanuatu", code: "VU", currencyCode: "VUV", flagEmoji: "🇻🇺"),
            Country(name: "Vatican City", code: "VA", currencyCode: "EUR", flagEmoji: "🇻🇦"),
            Country(name: "Venezuela", code: "VE", currencyCode: "VES", flagEmoji: "🇻🇪"),
            Country(name: "Vietnam", code: "VN", currencyCode: "VND", flagEmoji: "🇻🇳"),
            Country(name: "Yemen", code: "YE", currencyCode: "YER", flagEmoji: "🇾🇪"),
            Country(name: "Zambia", code: "ZM", currencyCode: "ZMW", flagEmoji: "🇿🇲"),
            Country(name: "Zimbabwe", code: "ZW", currencyCode: "ZWL", flagEmoji: "🇿🇼"),
        ]
    }
    
    static func getCountryBy(name: String) -> Country? {
        return countries.first { c in
            c.name.localizedLowercase == name.localizedLowercase
        }
    }
    
    static func getCountryBy(code: String) -> Country? {
        return countries.first { c in
            c.code.localizedLowercase == code.localizedLowercase
        }
    }
    
    static func getCountryBy(currencyCode: String) -> Country? {
        return countries.first { c in
            c.currencyCode.localizedLowercase == currencyCode.localizedLowercase
        }
    }
}
